### ISSUE TITLE
gilot plot コマンドで「ValueError: Invalid RGBA argument」エラーが出る

### ISSUE THREAD

**Issue by scrpgil** [hirokidaichi/gilot#1]
## 概要
`gilot plot -i repo.csv -o graph.png` コマンドで「ValueError: Invalid RGBA argument」のエラーがでます。

matplotlibのversionは3.1.3です。

<img width="1123" alt="Screen Shot 2020-06-04 at 18 55 31" src="https://user-images.githubusercontent.com/26167770/83742934-fbe9de00-a694-11ea-82b0-58db89e84233.png">

## 対処

ローカルで、以下の行の `#ccc` を `#cccccc` に書き換えたら動作しました。

https://github.com/hirokidaichi/gilot/blob/19419ef70681ca74d4e8acb7523e7489dbd63e3b/src/gilot/plot.py#L81

**Comment by hirokidaichi** [comment]
修正しました！ありがとうございます。

**Comment by scrpgil** [comment]
こちらこそありがとうございます！
