### ISSUE TITLE
`gilot log --full` にてマージコミットの差分ファイルが入ってしまう

### ISSUE THREAD

**Issue by tomingtoming** [hirokidaichi/gilot#10]
#8 の解消でlogにて出力されるCSVカラム `insertions`, `deletions`, `lines`, `files` は全て0になりましたが、 `--full` オプションを付与した際に出力される `files_json` に #8 同様にマージした内容の分の差分ファイルの情報が出力されます。

**Comment by hirokidaichi** [comment]
あああ！ありがとうございます。確認して修正します！
