### ISSUE TITLE
hotgraphのための引数を追加できるようにしてほしい

### ISSUE THREAD

**Issue by matoken78** [hirokidaichi/gilot#12]
プロジェクトの状況を確認するのに便利だと思い、利用させていただきました。
ありがとうございます。

ところで、hotgraph を networkx で表示する際に
ファイルパスが重なることで見えなくなることがあり、下記を引数として指定できると嬉しいと思いました。
- ノード間の反発力（k）
- フォントサイズ
- ファイルパスを"/"で改行するかどうか

もしよろしければ、プルリクエストを出させていただきたいのですが、いかがでしょうか？

**Comment by hirokidaichi** [comment]
おお。よさそうですね！ありがとうございます！ぜひpull requestなげてください！

**Comment by matoken78** [comment]
ありがとうございます！
pull request 出させていただきました！

**Comment by hirokidaichi** [comment]
mergeしました！
