### ISSUE TITLE
typo "repogitry"

### ISSUE THREAD

**Issue by fugaco** [hirokidaichi/gilot#2]
## 現象

以下2ヶ所に英単語のスペルミス `repogitry` がありました。

- README.md
- src/gilot/app.py

## 対処方法

- [ ] `README.md` の `repogitry` を `repository` に修正する
- [ ] `src/gilot/app.py` の `repogitry` を `repository` に修正する

**Comment by hirokidaichi** [comment]
修正しました！ありがとうございます！
